/**
 * Demo data, shaped exactly like the wire format the gateway will return.
 * It is deliberately untyped here — everything is parsed by `snapshotSchema`
 * before any screen sees it.
 */
export const SNAPSHOT: unknown = {
  account: {
    balanceMinor: 128_450_000,
    koboPerDollar: 158_000,
    paused: false,
  },
  contacts: [
    {
      id: 'c-mom',
      name: 'Mom',
      initials: 'M',
      phone: '+234 802 114 5510',
      place: 'Lagos',
      tone: 1,
    },
    {
      id: 'c-chidi',
      name: 'Chidi Okafor',
      initials: 'CO',
      phone: '+234 803 998 2210',
      place: 'Lagos · Zenith Bank',
      destination: 'Zenith Bank · ••4471',
      tone: 2,
    },
    {
      id: 'c-ada',
      name: 'Ada Eze',
      initials: 'AE',
      phone: '+234 806 447 1092',
      place: 'Enugu',
      tone: 1,
    },
    {
      id: 'c-tunde',
      name: 'Tunde Bello',
      initials: 'TB',
      phone: '+234 815 220 7741',
      place: 'Ibadan',
      tone: 3,
    },
    {
      id: 'c-ngozi-udo',
      name: 'Ngozi Udo',
      initials: 'NU',
      phone: '+234 809 663 4418',
      place: 'Abuja',
      tone: 1,
    },
    { id: 'c-aunt-ngozi', name: 'Aunt Ngozi', initials: 'NA', place: 'Owerri', tone: 2 },
    { id: 'c-emeka', name: 'Emeka Nwosu', initials: 'EN', place: 'London', tone: 3 },
  ],
  allowances: [
    {
      id: 'a-mom',
      name: 'Monthly transfer to Mom',
      recipientId: 'c-mom',
      limitMinor: 10_000_000,
      spentMinor: 5_000_000,
      perRunMinor: 5_000_000,
      cadence: 'monthly',
      resetsAt: '2026-10-01T00:00:00.000+01:00',
      paused: false,
    },
    {
      id: 'a-school',
      name: "Ada's school fees",
      recipientId: 'c-ada',
      limitMinor: 15_000_000,
      spentMinor: 13_150_000,
      perRunMinor: 13_150_000,
      cadence: 'monthly',
      resetsAt: '2026-10-01T00:00:00.000+01:00',
      paused: false,
    },
    {
      id: 'a-groceries',
      name: 'Family groceries',
      recipientId: 'c-ngozi-udo',
      limitMinor: 8_000_000,
      spentMinor: 800_000,
      perRunMinor: 800_000,
      cadence: 'weekly',
      resetsAt: '2026-10-01T00:00:00.000+01:00',
      paused: false,
    },
  ],
  activity: [
    {
      id: 'r-1',
      contactId: 'c-mom',
      note: 'Monthly transfer',
      at: '2026-09-02T09:04:00.000+01:00',
      amountMinor: 5_000_000,
      direction: 'out',
      initiatedBy: 'assistant',
      state: 'settled',
      allowanceId: 'a-mom',
    },
    {
      id: 'r-2',
      contactId: 'c-chidi',
      note: 'Rent share',
      at: '2026-09-01T18:20:00.000+01:00',
      amountMinor: 12_000_000,
      direction: 'out',
      initiatedBy: 'you',
      state: 'settled',
    },
    {
      id: 'r-3',
      contactId: 'c-ada',
      note: 'School fees',
      at: '2026-08-31T16:12:00.000+01:00',
      amountMinor: 13_150_000,
      direction: 'out',
      initiatedBy: 'assistant',
      state: 'settled',
      allowanceId: 'a-school',
    },
    {
      id: 'r-4',
      contactId: 'c-aunt-ngozi',
      note: 'Birthday',
      at: '2026-08-30T11:30:00.000+01:00',
      amountMinor: 850_000,
      direction: 'out',
      initiatedBy: 'you',
      state: 'settled',
    },
    {
      id: 'r-5',
      contactId: 'c-emeka',
      note: 'Received',
      at: '2026-08-29T20:02:00.000+01:00',
      amountMinor: 4_500_000,
      direction: 'in',
      initiatedBy: 'you',
      state: 'settled',
    },
  ],
  pots: [
    {
      id: 'p-lagos-trip',
      name: 'Lagos trip',
      targetMinor: 48_000_000,
      collectedMinor: 34_000_000,
      startedByYou: true,
      assistantNote: "I'll nudge Tunde and Ngozi on Friday if they haven't paid.",
      members: [
        {
          id: 'm-you',
          name: 'Adaeze (you)',
          initials: 'AE',
          tone: 1,
          paidMinor: 12_000_000,
          owedMinor: 0,
          isYou: true,
        },
        {
          id: 'm-chidi',
          name: 'Chidi Okafor',
          initials: 'CO',
          tone: 2,
          paidMinor: 12_000_000,
          owedMinor: 0,
          isYou: false,
        },
        {
          id: 'm-tunde',
          name: 'Tunde Bello',
          initials: 'TB',
          tone: 3,
          paidMinor: 10_000_000,
          owedMinor: 2_000_000,
          isYou: false,
        },
        {
          id: 'm-ngozi',
          name: 'Ngozi Udo',
          initials: 'NU',
          tone: 1,
          paidMinor: 0,
          owedMinor: 12_000_000,
          isYou: false,
        },
      ],
    },
  ],
  request: {
    id: 'q-1',
    requesterName: 'Adaeze',
    amountMinor: 7_500_000,
    note: 'Generator repair',
    link: 'entole.to/adaeze-75',
  },
  proposal: {
    id: 'pr-1',
    allowanceId: 'a-mom',
    contactId: 'c-mom',
    amountMinor: 5_000_000,
    note: 'Monthly transfer',
    undoSeconds: 8,
  },
};
